FROM maven:latest as maven_builder
RUN mkdir -p /app
WORKDIR /app
COPY pom.xml /app
RUN mvn -B dependency:resolve dependency:resolve-plugins
COPY src /app/src
RUN mvn package

FROM tomcat

EXPOSE 8080
WORKDIR /app
COPY target/javarush_game-1.0-SNAPSHOT.war .javarush_game-1.0.war
